2024-11-12 17:39:54,368 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "d:\github Urbanuniversity\Urban-university\module_12\tests_12_4.py", line 84, in test_run
    runner = Runner(123) # передаем число а не строку
             ^^^^^^^^^^^
  File "d:\github Urbanuniversity\Urban-university\module_12\tests_12_4.py", line 20, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-12 17:39:54,369 | WARNING | Неправильная скорость у runner
Traceback (most recent call last):
  File "d:\github Urbanuniversity\Urban-university\module_12\tests_12_4.py", line 72, in test_walk
    runner = Runner('Default1', speed = -1) #передаем отрицательную скорость
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\github Urbanuniversity\Urban-university\module_12\tests_12_4.py", line 25, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -1
